#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Andrew Diamond
url: 'https://andrew.diamonds'
baseurl: '' 
theme_skin: ceramic 
chrome_mobile_color: 

# Tracker
analytics: UA-98809834-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: localhost
safe: false
